### PR TITLE
Added autodiscovery mechnism for getting vagrant's full command list

### PR DESCRIPTION
**Pull request by soltysh**
I'm using vagrant with openshift plugin, so I'm having reacher list of commands available with vagrant. So I though it might be good idea to create such auto-discovery within your autocompletion. So here it is :)

### CODE REVIEW

**Comment by dobbymoodge** [comment]
@soltysh Shouldn't `etc/bash_completion.d/update` be located somewhere like `setup/update` or something? Otherwise, this seems to make sense as long as the subcommand extraction is robust.

**Comment by soltysh** [comment]
@dobbymoodge you're right, I've fixed it, by moving to suggested `setup` directory. I've also rebased the PR on top of recent master changes.

**Comment by dobbymoodge** [comment]
@kura any chance of a re-review with the recent changes?

**Comment by Mattias-** [comment]
:-1:
I'm not the repo owner but I do got some comments that I think should be addressed before merging.
- I do not think it's a great idea to have the commands being set during install. Then I have to `make install` every time commands are added/removed.
- Modifying source files with `sed` makes it hard to read/understand the source code.
- The feature to discover subcommands/flags should be put in a separate pull request.
I might sound negative but I do like the intent just not the way it's implemented!

**Comment by soltysh** [comment]
@Mattias- thx for you input :smile:. My initial goal was to do live reading of the subcommands, unfortunately vagrant response times were so long (and trust me that delay wasn't acceptable) I resigned of that idea at the time of writing it and created the autodiscovery mechanism during `make install`. 
I'm not sure why I haven't used the `list-commands`, though. I'll have a look if it's usable. Also the caching idea makes sense, I'll have a look at it, but I can't promise anything in short term :blush: 
As for the flags, well the project contains some of them, so I though of having them all, since the mechanics for that are in place, it's debatable, I can be convince to do it one way or the other.

**Comment by dobbymoodge** [comment]
@Mattias- +1 for `--machine-readable`. It would be nice if there were something equivalent for sub-subcommands (e.g. `box list`).

I don't think that caching is a good idea, because it's an unexpected side-effect, and potentially introduces a race condition<sup>**1**</sup>. I also think that rebuilding the subcommand list every time you hit "`tab`" is unacceptably slow.

I think the "`make install`" behavior is the least evil option here. It gets us up-to-date completion without sacrificing speed, and it ensures that any changes to the system made by this package are the result of user intent.

---------

**1**: This could be addressed using `mktemp` I suppose, but then users with multiple shells open might see different completion options after installing a new vagrant plugin. Another option would be to use a lockfile. I'll leave it up to @soltysh to determine if the added complexities from these techniques are acceptable/sustainable.

**Pull request closed without merging**
